// This file was auto-generated by ML.NET Model Builder. 

using System;
using CSharpPredictorML.Model;

namespace CSharpPredictorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Company = @"vaz",
                Model = 2107F,
                Mileage = 90000F,
                EnginePower = 75F,
                EngineVolume = 1.6F,
                Year = 2001F,
                Transmission = false,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");
            Console.WriteLine($"Company: {sampleData.Company}");
            Console.WriteLine($"Model: {sampleData.Model}");
            Console.WriteLine($"Mileage: {sampleData.Mileage}");
            Console.WriteLine($"EnginePower: {sampleData.EnginePower}");
            Console.WriteLine($"EngineVolume: {sampleData.EngineVolume}");
            Console.WriteLine($"Year: {sampleData.Year}");
            Console.WriteLine($"Transmission: {sampleData.Transmission}");
            Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
