// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CSharpPredictorML.Model
{
    public class ModelInput
    {
        [ColumnName("company"), LoadColumn(0)]
        public string Company { get; set; }


        [ColumnName("model"), LoadColumn(1)]
        public float Model { get; set; }


        [ColumnName("mileage"), LoadColumn(2)]
        public float Mileage { get; set; }


        [ColumnName("enginePower"), LoadColumn(3)]
        public float EnginePower { get; set; }


        [ColumnName("engineVolume"), LoadColumn(4)]
        public float EngineVolume { get; set; }


        [ColumnName("year"), LoadColumn(5)]
        public float Year { get; set; }


        [ColumnName("transmission"), LoadColumn(6)]
        public bool Transmission { get; set; }


        [ColumnName("link"), LoadColumn(7)]
        public string Link { get; set; }


        [ColumnName("price"), LoadColumn(8)]
        public float Price { get; set; }


    }
}
